/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.0/userguide/multi_project_builds.html
 */

rootProject.name = "samt-core"
include("cli")

dependencyResolutionManagement {
    versionCatalogs {
        val kotlin = "1.8.10"
        val shadow = "8.1.0"

        create("libs") {
            plugin("kotlin-jvm", "org.jetbrains.kotlin.jvm").version(kotlin)
            plugin("shadow", "com.github.johnrengelman.shadow").version(shadow)
        }

        create("testLibs") {
            library("kotlin-test", "org.jetbrains.kotlin", "kotlin-test-junit5").version(kotlin)
        }
    }
}
