/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tools.samt.cli

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        assertNotNull(App.greeting, "app should have a greeting")
    }
}
