package tools.samt.codegen.kotlin

import tools.samt.api.types.*

object KotlinGeneratorConfig {
    const val REMOVE_PREFIX_FROM_SAMT_PACKAGE = "removePrefixFromSamtPackage"
    const val ADD_PREFIX_TO_KOTLIN_PACKAGE = "addPrefixToKotlinPackage"
}

val GeneratedFilePreamble = """
    @file:Suppress("RemoveRedundantQualifierName", "unused", "UnusedImport", "LocalVariableName", "FunctionName", "ConvertTwoComparisonsToRangeCheck", "ReplaceSizeCheckWithIsNotEmpty", "NAME_SHADOWING", "UNUSED_VARIABLE", "NestedLambdaShadowedImplicitParameter", "KotlinRedundantDiagnosticSuppress")
    
    /*
     * This file is generated by SAMT, manual changes will be overwritten.
     * Visit the SAMT GitHub for more details: https://github.com/samtkit/core
     */
""".trimIndent()

internal fun String.replacePackage(options: Map<String, String>): String {
    val removePrefix = options[KotlinGeneratorConfig.REMOVE_PREFIX_FROM_SAMT_PACKAGE]
    val addPrefix = options[KotlinGeneratorConfig.ADD_PREFIX_TO_KOTLIN_PACKAGE]

    var result = this

    if (removePrefix != null) {
        result = result.removePrefix(removePrefix).removePrefix(".")
    }

    if (addPrefix != null) {
        result = "$addPrefix.$result"
    }

    return result
}

internal fun SamtPackage.getQualifiedName(options: Map<String, String>): String = qualifiedName.replacePackage(options)

internal fun TypeReference.getQualifiedName(options: Map<String, String>): String {
    val qualifiedName = type.getQualifiedName(options)
    return if (isOptional) {
        "$qualifiedName?"
    } else {
        qualifiedName
    }
}

internal fun Type.getQualifiedName(options: Map<String, String>): String = when (this) {
    is LiteralType -> when (this) {
        is StringType -> "String"
        is BytesType -> "ByteArray"
        is IntType -> "Int"
        is LongType -> "Long"
        is FloatType -> "Float"
        is DoubleType -> "Double"
        is DecimalType -> "java.math.BigDecimal"
        is BooleanType -> "Boolean"
        is DateType -> "java.time.LocalDate"
        is DateTimeType -> "java.time.LocalDateTime"
        is DurationType -> "java.time.Duration"
        else -> error("Unsupported literal type: ${this.javaClass.simpleName}")
    }

    is ListType -> "List<${elementType.getQualifiedName(options)}>"
    is MapType -> "Map<${keyType.getQualifiedName(options)}, ${valueType.getQualifiedName(options)}>"

    is UserType -> qualifiedName.replacePackage(options)

    else -> error("Unsupported type: ${javaClass.simpleName}")
}

internal fun UserType.getTargetPackage(options: Map<String, String>): String = qualifiedName.replacePackage(options).dropLastWhile { it != '.' }
