name: Publish Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build CLI
        run: ./gradlew --no-daemon :cli:shadowDistZip :cli:shadowDistTar :language-server:shadowJar

      - name: Rename cli-shadow to cli
        run: |
          mv cli/build/distributions/cli-shadow.zip cli/build/distributions/cli.zip
          mv cli/build/distributions/cli-shadow.tar cli/build/distributions/cli.tar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cli/build/distributions/cli.zip
            cli/build/distributions/cli.tar
            language-server/build/libs/samt-ls.jar
          fail_on_unmatched_files: true
          draft: true
          generate_release_notes: true

      - name: Publish to Sonatype OSSRH
        run: ./gradlew --no-daemon publishMavenPublicationToOSSRHRepository
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSWORD }}
